padding-x = 3
padding-y = [-25, 0]

[cursor]
shape = 'block'
blinking = true

[editor]
program = "nvim"
args = []

[window]
width = 1050
height = 650
opacity = 0.8
blur = true
decorations = "Buttonless"
macos-use-unified-titlebar = false

[renderer]
performance = "High"
backend = "Automatic"
disable-renderer-when-unfocused = false

[fonts]
size = 12
# family = "BlexMono Nerd Font"
# family = "CaskaydiaCove Nerd Font"
# family = "Hack Nerd Font"
# family = "Moralerspace Argon HWNF"
# family = "PlemolJP35 Console NF"
# family = "UDEV Gothic 35NF"
family = "Firple"
# family = "Bizin Gothic NF"
# family = "Explex Console NF"

[fonts.regular]
family = "Firple"
# family = "UDEV Gothic 35NF"
style = "Normal"
weight = 500

[fonts.bold]
family = "Firple"
# family = "UDEV Gothic 35NF"
style = "Normal"
weight = 1000

[fonts.italic]
family = "Firple"
# family = "UDEV Gothic 35NF"
style = "Italic"
weight = 500

[fonts.bold-italic]
family = "Firple"
# family = "UDEV Gothic 35NF"
style = "Italic"
weight = 1000

[fonts.emoji]
family = "Apple Color Emoji"
style = "Normal"

[fonts.ui]
family = "SF Pro"
style = "Normal"

[scroll]
multiplier = 3.0
divider = 1.0

[navigation]
# mode = "NativeTab"
# mode = "TopTab"
# mode = "BottomTab"
# mode = "Bookmark"
mode = "Plain"
clickable = true
hide-if-single = true
use-current-path = true
use-split = true
open-config-with-split = true

[shell]
program = "/bin/zsh"
args = ["--login"]

[colors]
# Regular colors
background = '#000000'
# background = '#101216' # GitHub Dark color
# background = '#0F0D0E' # Default Rio terminal color
black = '#15161e'
blue = '#7aa2f7'
cursor = '#c0caf5'
cyan = '#7dcfff'
foreground = '#c0caf5'
green = '#9ece6a'
magenta = '#bb9af7'
red = '#f7768e'
white = '#a9b1d6'
yellow = '#e0af68'

# Navigation
tabs = '#12B5E5'
tabs-foreground = '#707070'
tabs-active = '#151515'
# tabs-active-highlight = '#000000'
tabs-active-highlight = '#f712ff'
# tabs-active-highlight = '#ff1545'
# tabs-active-highlight = '#FF007C'
# tabs-active-foreground = '#c0caf5'
tabs-active-foreground = '#ffffff'
bar = '#000000'

# Search
search-match-background = '#44C9F0'
search-match-foreground = '#FFFFFF'
search-focused-match-background = '#E6A003'
search-focused-match-foreground = '#FFFFFF'

# Selection
selection-background = '#33467c'
selection-foreground = '#c0caf5'

# Light colors
light-black = '#414868'
light-blue = '#7aa2f7'
light-cyan = '#7dcfff'
light-green = '#9ece6a'
light-magenta = '#bb9af7'
light-red = '#f7768e'
light-white = '#c0caf5'
light-yellow = '#e0af68'
