git:
  branchPrefix: "shuheykoyama/"
  paging:
    # externalDiffCommand: "difft --color=always"
    colorArg: always
    pager: delta --dark --paging=never
  mainBranches:
    - "main"
    - "master"
    - "develop"
  parseEmoji: true

# tokyonight_night
gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#ff9e64"
      - "bold"
    inactiveBorderColor:
      - "#27a1b9"
    searchingActiveBorderColor:
      - "#ff9e64"
      - "bold"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#283457"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#bb9af7"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#e0af68"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"
# gui:
#   nerdFontsVersion: "3"
#   theme:
#     activeBorderColor:
#       - "#c94c16"
#       - "bold"
#     inactiveBorderColor:
#       - "#664c00"
#     searchingActiveBorderColor:
#       - "#c94c16"
#       - "bold"
#     optionsTextColor:
#       - "#268bd3"
#     selectedLineBgColor:
#       - "#1a6397"
#     cherryPickedCommitFgColor:
#       - "#268bd3"
#     cherryPickedCommitBgColor:
#       - "#d23681"
#     markedBaseCommitFgColor:
#       - "#268bd3"
#     markedBaseCommitBgColor:
#       - "#b28500"
#     unstagedChangesColor:
#       - "#f55350"
#     defaultFgColor:
#       - "#839395"
  authorColors:
    "*": "#b4befe"
  showIcons: true

confirmOnQuit: true
quitOnTopLevelReturn: true

customCommands:
  - key: "c"
    command: "czg ai"
    description: "commit with AI powered commitizen"
    context: "files"
    loadingText: "opening AI powered commitizen commit tool"
    subprocess: true
  - key: "C"
    command: "git cz"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
