palette = "catppuccin_mocha"

format = """
$directory\
$git_branch\
$git_status\
$java\
$nodejs\
$package\
$php\
$python\
$rust\
$fill\
$cmd_duration\
$time
$character\
"""

add_newline = true

[character]
disabled = false
success_symbol = '[  ](bold #56d364)'
error_symbol = '[  ](bold #f78166)'
format = '$symbol'

[cmd_duration]
disabled = false
min_time = 500
show_milliseconds = true
format = '[took ](fg:white)[$duration ](fg:peach)'

[directory]
format = '[ $path ](fg:blue)'
read_only = " "
truncation_length = 3
fish_style_pwd_dir_length = 3

[fill]
disabled = false
symbol = ' '

[git_branch]
symbol = "[ ](mauve)"
format = '[on ](fg:white)[$symbol](fg:mauve)[$branch ](fg:mauve)'

[git_status]
style = "fg:text bg:surface0"
format = '[$all_status$ahead_behind ](fg:red)'

[time]
disabled = false
time_format = "%T"
format = '[at ](fg:white)[$time ](fg:yellow)'

[c]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[java]
symbol = " "

[lua]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = "󰏗 "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
