format = """
$directory\
$git_branch\
$git_status\
$package\
$golang\
$java\
$nodejs\
$php\
$python\
$rust\
$docker_context\
$cmd_duration
$character\
"""

add_newline = true
palette = "tokyonight"

[c]
symbol = " "

[dart]
symbol = " "

[directory]
truncation_length = 3
truncation_symbol = "~"
truncate_to_repo = false
fish_style_pwd_dir_length = 3
home_symbol = "~"
read_only = " "
format = "[$path ](fg:blue)[$read_only]($read_only_style)"
before_repo_root_style = "fg:blue"
repo_root_style = "bold fg:blue"
repo_root_format = "[$before_root_path]($before_repo_root_style)[$repo_root$path ]($repo_root_style)[$read_only]($read_only_style)"

[docker_context]
symbol = " "
format = "[via ](fg:foreground)[$symbol$context]($style) "

[git_branch]
symbol = " "
format = "[on ](fg:foreground)[$symbol$branch(:$remote_branch)]($style) "

[git_status]
# ahead = '⇡${count}'
# behind = '⇣${count}'
# untracked = '?${count}'
# modified = '!${count}'
# format = '[$all_status$ahead_behind]($style) '

[character]
success_symbol = '[❯](green)'
error_symbol = '[❯](red)'

[cmd_duration]
min_time = 1
style = 'fg:yellow'
format = "[took ](fg:foreground)[ $duration]($style)"

[golang]
symbol = " "

[haskell]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[lua]
symbol = " "

[nodejs]
symbol = " "
# symbol = " "
format = "[via ](fg:foreground)[$symbol$version]($style) "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[package]
symbol = " "
format = "[is ](fg:foreground)[$symbol$version]($style) "

[php]
symbol = " "
format = "[via ](fg:foreground)[$symbol$version]($style) "

[python]
symbol = " "
format = '[via ](fg:foreground)[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
pyenv_version_name = false

[ruby]
symbol = " "

[rust]
symbol = " "

[palettes.tokyonight]
background = '#101216'
foreground = '#8b949e'
selection-background = '#3b5070'
selection-foreground = '#ffffff'
black = '#000000'
red = '#f78166'
green = '#56d364'
yellow = '#e3b341'
blue = '#6ca4f8'
magenta = '#db61a2'
cyan = '#2b7489'
white = '#ffffff'
