palette = "catppuccin_mocha"

format = """
[ ┌─ ](surface1)\
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$time\
[ ─┐ ](surface1)
[ └──](surface1)\
$character\
"""

right_format = """
[──┘](surface1)
"""

add_newline = true

[directory]
style = "fg:text bg:surface0"
format = "[](fg:blue)[󰝰 ](fg:mantle bg:blue)[ $path]($style)[ ](fg:surface0)"
truncation_length = 3
fish_style_pwd_dir_length = 3

[git_branch]
symbol = ""
style = "fg:text bg:surface0"
format = '[](fg:mauve)[$symbol ](fg:mantle bg:mauve)[ $branch]($style)'

[git_status]
style = "fg:text bg:surface0"
format = '[ $all_status$ahead_behind]($style)[ ](fg:surface0)'

[cmd_duration]
disabled = false
min_time = 500
show_milliseconds = true
style = 'fg:text bg:surface0'
format = '[ ](fg:peach)[󱦟 ](fg:mantle bg:peach)[ $duration]($style)[](fg:surface0)'

[time]
disabled = false
time_format = "%T"
style = "fg:text bg:surface0"
format = '[ ](fg:text)[󱑎 ](fg:mantle bg:text)[ $time]($style)[](fg:surface0)'

[character]
disabled = false
success_symbol = '[ ❯ ](bold teal)'
error_symbol = '[ ❯ ](bold red)'
format = '$symbol'

[fill]
disabled = false
symbol = '─'
style = 'fg:surface1'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
