format = """
[┌─](#666666)\
[](#3c3c3c)\
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$time\
[](fg:#3c3c3c)
[└──](#666666)\
$character\
"""

add_newline = true

[directory]
style = "bold fg:#2a84d2 bg:#3c3c3c"
format = "[ $path ]($style)[](fg:#3c3c3c)"
truncation_length = 3
fish_style_pwd_dir_length = 3

[git_branch]
symbol = ""
style = "fg:#131313 bg:#4e5ab7"
format = '[ $symbol $branch]($style)'

[git_status]
style = "fg:#131313 bg:#4e5ab7"
format = '[ $all_status$ahead_behind ]($style)[](fg:#4e5ab7)'

[cmd_duration]
disabled = false
min_time = 500
show_milliseconds = true
style = 'fg:#131313 bg:#ecba0f'
format = '[](fg:#ecba0f)[ $duration ]($style)'

[time]
disabled = false
time_format = "%T"
style = "fg:#d6dbe5 bg:#3c3c3c"
format = '[](fg:#3c3c3c)[ $time ]($style)'

[character]
disabled = false
success_symbol = '[❯ ](bold green)'
error_symbol = '[❯ ](bold red)'
format = '$symbol'

[fill]
disabled = false
symbol = '─'
style = 'fg:#666666'
