format = """
[](fg:black)\
$os\
[](fg:black bg:#333333)\
$directory\
$git_branch\
$git_status\
[](fg:#333333)\
$fill\
[](fg:#333333)\
$cmd_duration\
$time\
[](fg:#333333)
$character\
"""

right_format = """
$golang\
$java\
$nodejs\
$php\
$python\
$rust\
$docker_context\
"""

add_newline = true

palette = "tokyonight"

[os]
format = "[$symbol]($style)"
style = 'fg:foreground bg:black'
disabled = false

[os.symbols]
Macos = "  "

[directory]
truncation_length = 3
truncation_symbol = " ~"
truncate_to_repo = false
fish_style_pwd_dir_length = 3
home_symbol = " ~"
style = "bold fg:cyan bg:#333333"
read_only = " 󰌾 "
read_only_style = "fg:red bg:#333333"
format = "[ $path ]($style)[$read_only]($read_only_style)"

[git_branch]
symbol = ' '
truncation_symbol = ''
style = 'fg:magenta bg:#333333'
format = '[](fg:cyan bg:#333333)[ $symbol$branch(:$remote_branch)]($style)'

[git_status]
style = 'fg:magenta bg:#333333'
conflicted = '='
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕'
up_to_date = '✓'
untracked = '?'
stashed = '$'
modified = '!${count}'
renamed = '»'
deleted = '✘'
format = '[ $all_status$ahead_behind ]($style)'

[fill]
symbol = ' '
style = '#333333'

[character]
#    ❯ 󰳓
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'

[cmd_duration]
min_time = 1
style = 'fg:yellow bg:#333333'
format = "[  $duration]($style)[ ](fg:foreground bg:#333333)"

[time]
disabled = false
style = 'fg:foreground bg:#333333'
format = '[  $time]($style)'
time_format = '%T'
utc_time_offset = '+9'

[python]
symbol = ' '
format = '[  ${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)'
pyenv_version_name = false
style = 'fg:yellow'

[rust]
symbol = ""
format = '[  $symbol $version](red)'

[nodejs]
symbol = ""
format = '[  $symbol $version](green)'

[java]
symbol = "󰛊"
format = '[  $symbol $version](red)'

[php]
symbol = ""
format = '[  $symbol $version](magenta)'

[golang]
symbol = ""
format = '[  $symbol $version](cyan)'

[docker_context]
symbol = "󰡨"
format = '[  $symbol $context](cyan)'

[palettes.tokyonight]
background = '#1a1b26'
foreground = '#c0caf5'
selection-background = '#33467c'
selection-foreground = '#c0caf5'
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'
